#!/bin/bash
#
# Author	Yann Bayle
# E-mail	bayle.yann@live.fr
# License   MIT
# Created	19/09/2016
# Updated	28/09/2016
# Version	2
# Object	Clean all objects generated by gaiaWrapper.py
#

rm -r ./data/datasets
rm -r ./data/results
rm ./data/*.yaml
rm ./data/ins/*.sig
rm ./data/ins/*.json
rm ./data/voc/*.sig
rm ./data/voc/*.json
rm ./data/.project
